spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=SQLEXPRESS;Database=master;Trusted_Connection=True;
    username: sa
    password: Projects@123
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl